### ISSUE TITLE
Landscape Video Recording Problem on iPhone 8 Running iOS 14.2

### ISSUE THREAD

**Issue by pandraos** [gorastudio-git/SCNRecorder#20]
Hello,

I encountered an unusual issue while working with SCNRecorder.

Videos recorded in landscape orientation on iPhone 8 specifically running iOS 14.2 are rotated sideways and almost look as if they were recorded in locked portrait mode.
Videos recorded in portrait orientation work just fine.

It is a bit difficult to properly describe this issue so please refer to the three screenshots below.

<details>
  <summary>Preview of Video Recorded in Portrait Mode</summary>

![portrait](https://user-images.githubusercontent.com/22884716/100855352-be72db80-3492-11eb-9695-161e07bb8fd2.PNG)

</details>

<details>
  <summary>Preview of Video Recorded in Landscape Left Mode</summary>

![landscape-left](https://user-images.githubusercontent.com/22884716/100855627-0c87df00-3493-11eb-8c59-d4a03bc374ce.PNG)

</details>

<details>
  <summary>Preview of Video Recorded in Landscape Right Mode</summary>

![landscape-right](https://user-images.githubusercontent.com/22884716/100855743-33461580-3493-11eb-9846-ed7ecfd27da9.PNG)

</details>

I am using version 2.3.0 of SCNRecorder.

I have failed to replicate this issue on the following devices:
- iPhone 7 running iOS 13.6.
- iPhone 11 Pro running iOS 14.2
- iPad Pro 12.9'' (2015) running iPadOS 14.2

I have also attempted to play around with the video settings (specifically the size and the scaling mode) rather than using the default video settings but that didn't seem to help.

Thank you in advance for looking into this.

**Comment by v-grigoriev** [comment]
Hi @pandraos! 
The expectation was to see full-screen videos when recorded in the landscape modes?
May I ask you to upload videos? They have metadata that might help.

**Comment by pandraos** [comment]
The problem is that the videos shot in landscape mode on iPhone 8 (iOS 14.2) have the wrong orientation (rotated sideways) and are cropped to fit a portrait aspect ratio.

To illustrate the problem, I recorded the same video sequence using the same build of the app on two different phones in both landscape orientations:

- **The Issue:** iPhone 8 - iOS 14.2: https://gofile.io/d/IhS4hL

- **Expected Result:** iPhone 11 Pro - iOS 14.2: https://gofile.io/d/UPucYH

I hope this helps clear up the issue.

Thank you.

**Comment by pandraos** [comment]
Hi @v-grigoriev!
Have you found any clues regarding this issue?
Thanks again!

**Comment by v-grigoriev** [comment]
I know where is the issue and probably how to fix it, but absolutely don't have time. 
I'm postponing this till the next year since percent of affected apps and devices is low.

**Comment by pandraos** [comment]
@v-grigoriev Thanks for the update.

**Comment by itershukov** [comment]
We have the same issue with iPhone 12 pro, but in our case we have a flipped and mirrored video. 
![image](https://user-images.githubusercontent.com/14214562/119362653-9a5fbc80-bcb5-11eb-99a5-d54b29a68309.png)
Is there any updates?

**Comment by v-grigoriev** [comment]
No updates so far, but I can reprioritize this.
You can help me if build a simple app (probably modify the example app) so I have exact things to fix.

**Comment by itershukov** [comment]
Ok, we will provide it asap.

**Comment by DragonSpirit** [comment]
Hello! I've made a reproducible demo based on an example app: https://github.com/DragonSpirit/SCNRecorder

**Comment by v-grigoriev** [comment]
Thank you! I will take a look.

**Comment by v-grigoriev** [comment]
There are two unrelated issues.
The first one is known and related to a video orientation.
The second, new one, is related to the changed underlying iosurface size/behavior.

I have a fix, I will share it in a few days when I finish verifying.

**Comment by itershukov** [comment]
When it will be ready we will check it on all of our devices (7, SE, 11 and 12) iphones.

**Comment by itershukov** [comment]
Hey, @v-grigoriev! Is there any news?

**Comment by v-grigoriev** [comment]
@itershukov Well, I can't find an absolute fix for now and I will be very busy for the next few weeks.

But, I have a **temporal solution**.
If u take the version from the **develop** branch.
And somewhere in your `viewDidLoad` set ` (sceneView.layer as? CAMetalLayer)?.framebufferOnly = false` it will work as expected. At least as far as I tested it look good.
I never saw any drawbacks on setting `framebufferOnly` to false.

In general, I can't find a universal fix for now, since on different devices it behaves differently. Since I can't find any background info or documentation I will need to investigate deeper. It will take time.

**Comment by v-grigoriev** [comment]
If someone wants to help me the issue is:

If `framebufferOnly` is set to `true` the underlying iosurface has "portrait" orientation even if the texture has "landscape" orientation. And the orientation is different on different iOS versions or devices (I tested on SE with 14.0.1 and 12  with 14.5).

**Comment by giomurru** [comment]
Hi there, I had the same problem with iPad iOS 15.5 on iPad 9th Gen, but not with iOS 15.5 on iPhone X.
Setting `framebufferOnly` to `false` solved the issue with incorrect orientation of the video.
The best is to set it just before starting the recording and setting it to true right after, because documentation says it affects performance when false. 
[https://developer.apple.com/documentation/quartzcore/cametallayer/1478168-framebufferonly](https://developer.apple.com/documentation/quartzcore/cametallayer/1478168-framebufferonly) 
However as stated by the documentation we need to set it to false while recording in order to support sampling and pixel read/write operations to the textures.
